[versions]
junit-jupiter = "5.10.2"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
